In [9]:
import numpy as np

"""
Performs tikhonov regularized least squares
I.e. solution of y = Ax for x
Parameters:
    A: NxM ndarray
    y: NxK ndarray
    mue: double
        regularization parameter
Returns:
    x: MxK array
"""
def lstsq_reg(A,Y,mue):
    Ac = np.copy(A)
    Yc = np.copy(Y)
    result = np.dot(np.dot(np.linalg.inv(
                            (Ac.T).dot(Ac)
                            +mue*np.eye(np.shape(Ac)[1])),
                        Ac.T),
                    Yc)
    return result

A=[[np.random.random() for M in range(200)] for N in range(200)]
y=[[np.random.random() for K in range(3)] for N in range(200)]
L=lstsq_reg(A,y,1)
print L

[[ -4.75869749e-02  -1.64025404e-02   7.24492625e-02]
 [  9.35348802e-02   5.04595530e-02  -3.31161875e-03]
 [  1.01333176e-01  -6.90610238e-02  -1.15746489e-02]
 [ -1.51541001e-01  -7.88346058e-02   5.13106896e-02]
 [  1.26732604e-02   4.59277063e-02   3.67249047e-02]
 [ -1.56529139e-02   1.37549767e-01  -1.29339351e-03]
 [  7.08478864e-02  -8.10072528e-03  -2.93216568e-02]
 [ -5.08910166e-02  -8.68019020e-02  -2.34106748e-01]
 [ -7.86357367e-03  -1.93967776e-02   2.97937926e-02]
 [  9.53159860e-03   1.20641004e-01  -5.61163048e-02]
 [  3.55577875e-02  -6.48138873e-03  -7.83696930e-03]
 [ -1.08342559e-01  -5.81769902e-02   7.78367957e-02]
 [ -4.68393388e-02   1.11956260e-01   8.38362638e-02]
 [  1.08277632e-01  -1.10803153e-02   1.02635009e-01]
 [ -2.36609043e-02   6.74246241e-02   3.61565659e-02]
 [ -3.46248476e-03   2.91565110e-02  -6.79783216e-02]
 [  1.05205511e-01  -9.42661957e-02  -5.11806186e-02]
 [ -1.11412883e-01   6.78860835e-02   2.84229617e-02]
 [  5.69213044e-02  -9.39720